export const CONTACT_EMAIL = 'khaanii654321@gmail.com'

export const categories = [
  {
    id: 'weddings',
    title: 'Luxury Weddings',
    blurb: 'End-to-end styling for ceremonies that feel like heirlooms.',
    from: 8500,
  },
  {
    id: 'corporate',
    title: 'Corporate Summits',
    blurb: 'Boardroom precision for launches, offsites, and shareholder events.',
    from: 12000,
  },
  {
    id: 'dinners',
    title: 'Private Dinners',
    blurb: 'Intimate tablescapes for twelve guests or fewer.',
    from: 3200,
  },
  {
    id: 'fashion',
    title: 'Fashion Shows',
    blurb: 'Runway logistics, lighting design, and front-row seating charts.',
    from: 15500,
  },
  {
    id: 'birthdays',
    title: 'Milestone Birthdays',
    blurb: 'Themed celebrations built around the decade being toasted.',
    from: 4800,
  },
  {
    id: 'launches',
    title: 'Brand Launches',
    blurb: 'Press-ready activations engineered for the first impression.',
    from: 9800,
  },
]

export const planners = [
  {
    id: 'aria-costantini',
    name: 'Aria Costantini Events',
    city: 'Lahore',
    category: 'Luxury Weddings',
    budgetTier: '$$$',
    rating: 4.9,
    reviews: 128,
    tags: ['Weddings', 'Floral Design', 'Destination'],
    price: 8500,
    availability: ['Sep 12', 'Sep 19', 'Oct 03'],
  },
  {
    id: 'summit-and-co',
    name: 'Summit & Co. Productions',
    city: 'Karachi',
    category: 'Corporate Summits',
    budgetTier: '$$$$',
    rating: 4.8,
    reviews: 76,
    tags: ['Corporate', 'AV Production', 'Staging'],
    price: 12000,
    availability: ['Aug 22', 'Sep 05', 'Sep 26'],
  },
  {
    id: 'the-lantern-table',
    name: 'The Lantern Table',
    city: 'Islamabad',
    category: 'Private Dinners',
    budgetTier: '$$',
    rating: 5.0,
    reviews: 54,
    tags: ['Dinners', 'Tablescapes', 'Chef Pairing'],
    price: 3200,
    availability: ['Aug 09', 'Aug 16', 'Aug 30'],
  },
  {
    id: 'noir-runway-studio',
    name: 'Noir Runway Studio',
    city: 'Lahore',
    category: 'Fashion Shows',
    budgetTier: '$$$$',
    rating: 4.7,
    reviews: 41,
    tags: ['Fashion', 'Lighting', 'Runway Build'],
    price: 15500,
    availability: ['Oct 10', 'Oct 24', 'Nov 07'],
  },
  {
    id: 'gilded-hour',
    name: 'Gilded Hour Celebrations',
    city: 'Faisalabad',
    category: 'Milestone Birthdays',
    budgetTier: '$$',
    rating: 4.9,
    reviews: 97,
    tags: ['Birthdays', 'Themed Decor', 'Entertainment'],
    price: 4800,
    availability: ['Aug 14', 'Sep 01', 'Sep 15'],
  },
  {
    id: 'firstlook-activations',
    name: 'FirstLook Activations',
    city: 'Karachi',
    category: 'Brand Launches',
    budgetTier: '$$$$',
    rating: 4.8,
    reviews: 63,
    tags: ['Launches', 'PR Staging', 'Experiential'],
    price: 9800,
    availability: ['Sep 08', 'Sep 22', 'Oct 06'],
  },
  {
    id: 'ivory-and-oak',
    name: 'Ivory & Oak Weddings',
    city: 'Gujrat',
    category: 'Luxury Weddings',
    budgetTier: '$$$',
    rating: 4.9,
    reviews: 84,
    tags: ['Weddings', 'Outdoor', 'Floral Design'],
    price: 9200,
    availability: ['Sep 26', 'Oct 10', 'Oct 24'],
  },
  {
    id: 'apex-conclave',
    name: 'Apex Conclave Group',
    city: 'Islamabad',
    category: 'Corporate Summits',
    budgetTier: '$$$',
    rating: 4.6,
    reviews: 39,
    tags: ['Corporate', 'Offsites', 'Delegate Logistics'],
    price: 10500,
    availability: ['Aug 18', 'Sep 01', 'Sep 15'],
  },
  {
    id: 'the-glass-room',
    name: 'The Glass Room Collective',
    city: 'Lahore',
    category: 'Private Dinners',
    budgetTier: '$$$',
    rating: 4.8,
    reviews: 46,
    tags: ['Dinners', 'Wine Pairing', 'Intimate'],
    price: 4100,
    availability: ['Aug 12', 'Aug 26', 'Sep 09'],
  },
]
